name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Print a greeting
      env:
        MY_VAR: Hi there2! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - run: |
        mkdir bthang
        cd bthang
        echo "this is file1" > file1.txt
        cat file1.txt
        cd ..
    - run: cat bthang/file1.txt

    - name: my upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          bthang
